version: "3"
   
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: django
    command: gunicorn dmtest.wsgi --bind 0.0.0.0:8000 --workers=3
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db